services:
  auth-gateway:
    build: auth-gateway
    ports:
      - "3000:3000"
    volumes:
      -  ./auth-gateway/src:/usr/src/app/src
    command: pnpm run start:dev
  activity-log:
    build: activity-log
    volumes:
      -  ./activity-log/src:/usr/src/app/src
    command: pnpm run start:dev
  nats:
    image: nats:latest
    ports:
      - "4222:4222"

