services:
  auth-gateway:
    build: auth-gateway
    command: pnpm run start:prod
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    env_file:
      - .env
    networks:
      - opengrad
    develop:
      watch:
        - action: sync
          path: ./auth-gateway
          target: /app/authgateway
          ignore:
            - ./authgateway/node_modules/
        - action: rebuild
          path: ./authgateway/package.json
  activity-log:
    build: activity-log
    command: pnpm run start:prod
    depends_on:
      - postgres
    env_file:
      - .env
    networks:
      - opengrad
    develop:
      watch:
        - action: sync
          path: ./activity-log
          target: /app/activitylog
          ignore:
            - ./activitylog/node_modules/
        - action: rebuild
          path: ./activitylog/package.json   
  forms:
    build: forms
    command: pnpm run start:prod
    depends_on:
      - postgres
    env_file:
      - .env
    networks:
      - opengrad
    develop:
      watch:
        - action: sync
          path: ./forms
          target: /app/forms
          ignore:
            - ./forms/node_modules/
        - action: rebuild
          path: ./forms/package.json
  notification:
    build: notification
    command: pnpm run start:prod
    depends_on:
      - postgres
    env_file:
      - .env
    networks:
      - opengrad
    develop:
      watch:
        - action: sync
          path: ./notification
          target: /app/notification
          ignore:
            - ./notification/node_modules/
        - action: rebuild
          path: ./notification/package.json
  nats:
    image: nats:latest
    ports:
      - "4222:4222"
    networks:
      - opengrad
  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    networks:
      - opengrad
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}

networks:
  opengrad:
    driver: bridge

