services:
  auth-gateway:
    build: auth-gateway
    ports:
      - "3000:3000"
    volumes:
      -  ./auth-gateway/src:/usr/src/app/src
    command: pnpm run start:prod
  activity-log:
    build: activity-log
    volumes:
      -  ./activity-log/src:/usr/src/app/src
    command: pnpm run start:prod
  forms:
    build: forms
    volumes:
      -  ./forms/src:/usr/src/app/src
    command: pnpm run start:prod
  notification:
    build: notification
    volumes:
      - ./notification/src:/usr/src/app/src
    command: pnpm run start:prod
  nats:
    image: nats:latest
    ports:
      - "4222:4222"

