services:
  auth-gateway:
    image: 590184147569.dkr.ecr.ap-south-1.amazonaws.com/auth-gateway:latest
    ports:
      - "5001:5001"
    env_file:
      - .env
    networks:
      - opengrad
  activity-log:
    image: 590184147569.dkr.ecr.ap-south-1.amazonaws.com/activity-log:latest
    env_file:
      - .env
    networks:
      - opengrad
  forms:
    image: 590184147569.dkr.ecr.ap-south-1.amazonaws.com/forms:latest
    env_file:
      - .env
    networks:
      - opengrad
  notification:
    image: 590184147569.dkr.ecr.ap-south-1.amazonaws.com/notification:latest
    env_file:
      - .env
    networks:
      - opengrad
  nats:
    image: nats:latest
    ports:
      - "4222:4222"
    networks:
      - opengrad
networks:
  opengrad:
    driver: bridge
