name: Deploy to ECS

on:
  push:
    paths:
      - 'authgateway/**'
      - 'activity-log/**'
      - 'forms/**'
      - 'notification/**'
    branches:
      - feat/deploy

env:
  AWS_REGION: us-east-1
  AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_ECS_CLUSTER: ${{ secrets.AWS_ECS_CLUSTER }}
  AWS_ECS_SERVICE: ${{ secrets.AWS_ECS_SERVICE }}
  AWS_ECR_REPOSITORY: ${{ secrets.AWS_ECR_REPOSITORY }} 

