# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# GitHub recommends pinning actions to a commit SHA.
# To get a newer version, you will need to update the SHA.
# You can also reference a tag or branch, but the action may change without warning.

name: Deploy to Amazon ECS

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME}}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Auth-gateway
        uses: docker/build-push-action@v5
        with:
          context: ./auth-gateway
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/auth-gateway:latest

      - name: Build and push Activity-log
        uses: docker/build-push-action@v5
        with:
          context: ./activity-log
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/activity-log:latest

      - name: Build and push Forms
        uses: docker/build-push-action@v5
        with:
          context: ./forms
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/forms:latest

      - name: Build and push Notification
        uses: docker/build-push-action@v5
        with:
          context: ./notification
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/notification:latest

      - name: Log out from Docker Hub
        run: docker logout
